# Generated by Django 4.1.11 on 2023-11-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kulutus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(default='', max_length=100)),
                ('hinta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lasku_päivämäärä', models.DateTimeField()),
            ],
        ),
    ]
