# Generated by Django 4.1.11 on 2023-11-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kulutus',
            name='lasku_päivämäärä',
            field=models.DateField(),
        ),
    ]
